# Generated by Django 5.2.3 on 2025-07-01 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('subtasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasks',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtasks',
            name='Content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'tasks'), ('model', 'tasks')), models.Q(('app_label', 'goals'), ('model', 'goals')), models.Q(('app_label', 'habits'), ('model', 'habits')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
