# Generated by Django 5.2.3 on 2025-07-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtasks', '0002_subtasks_object_id_alter_subtasks_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtasks',
            old_name='Content_type',
            new_name='content_type',
        ),
    ]
