# Generated by Django 5.2.3 on 2025-07-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtasks', '0004_subtask_delete_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
