# Generated by Django 5.2.3 on 2025-08-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluído'), ('F', 'Falhado')], default='P', max_length=1),
        ),
    ]
